#pragma once

#include "types.hpp"
#include <cmath>
#include <numbers>

/*
Side note :
BGFX rotation order is : YXZ
**/

/*
    Disclamer :
    - File mostly generated by AI, and reviewed by human.

*/

namespace Math
{

    /// @brief Mutiplication of two quaternions
    /// @param q1 first quaternion
    /// @param q2 second quaternion
    /// @return rotated quaternion
    inline Types::Vec4 multiplyQuat(const Types::Vec4 &q1, const Types::Vec4 &q2)
    {
        return Types::Vec4{
            q1.w * q2.x + q1.x * q2.w + q1.y * q2.z - q1.z * q2.y,
            q1.w * q2.y - q1.x * q2.z + q1.y * q2.w + q1.z * q2.x,
            q1.w * q2.z + q1.x * q2.y - q1.y * q2.x + q1.z * q2.w,
            q1.w * q2.w - q1.x * q2.x - q1.y * q2.y - q1.z * q2.z};
    };

    /// @brief Conjugate of a quaternion
    /// @param q original quaternion
    /// @return conjugated quaternion
    inline Types::Vec4 conjugateQuat(const Types::Vec4 &q)
    {
        return Types::Vec4{-q.x, -q.y, -q.z, q.w};
    };

    /// @brief Convert euler to quaternion using bgfx default order
    /// @param eulerRadians euler angle
    /// @return quaternion
    inline Types::Vec4 eulerToQuaternion(const Types::Vec3 &eulerRadians)
    {
        const float halfPitch = eulerRadians.x * 0.5f; // X
        const float halfYaw = eulerRadians.y * 0.5f;   // Y
        const float halfRoll = eulerRadians.z * 0.5f;  // Z

        const float cx = std::cos(halfPitch);
        const float sx = std::sin(halfPitch);
        const float cy = std::cos(halfYaw);
        const float sy = std::sin(halfYaw);
        const float cz = std::cos(halfRoll);
        const float sz = std::sin(halfRoll);

        return Types::Vec4{
            cy * sx * cz + sy * cx * sz, // x
            sy * cx * cz - cy * sx * sz, // y
            cy * cx * sz - sy * sx * cz, // z
            cy * cx * cz + sy * sx * sz  // w
        };
    };

    /// @brief Rotate one quaterion with another one
    /// @param q1 First quaternion
    /// @param q2 Second quaternion
    /// @return rotated quaternion
    inline Types::Vec4 combineRotations(const Types::Vec4 &q1, const Types::Vec4 &q2)
    {
        return multiplyQuat(q1, q2);
    }

    /// @brief Normalize a quaternion
    /// @param q quaternion
    /// @return normalized quaterion
    inline Types::Vec4 normalizeQuat(const Types::Vec4 &q)
    {
        const float length = std::sqrt(q.x * q.x + q.y * q.y + q.z * q.z + q.w * q.w);
        if (length > 0.0f)
        {
            const float invLength = 1.0f / length;
            return Types::Vec4{q.x * invLength, q.y * invLength, q.z * invLength, q.w * invLength};
        }
        return Types::Vec4{0.0f, 0.0f, 0.0f, 1.0f}; // Quaternion identity
    }

    /// @brief Convert quaternion to euler
    /// @param q Quaternion
    /// @return euler angle
    inline Types::Vec3 quaternionToEuler(const Types::Vec4 &q)
    {
        Types::Vec3 euler;
        constexpr float HALF_PI = std::numbers::pi_v<float> / 2.0f;

        Types::Vec4 qn = normalizeQuat(q);

        const float sinPitch = 2.0f * (qn.w * qn.x - qn.y * qn.z);

        if (sinPitch >= 0.99999f)
        {
            euler.x = HALF_PI;
            euler.y = 2.0f * std::atan2(qn.y, qn.w);
            euler.z = 0.0f;
        }
        else if (sinPitch <= -0.99999f)
        {
            euler.x = -HALF_PI;
            euler.y = 2.0f * std::atan2(qn.y, qn.w);
            euler.z = 0.0f;
        }
        else
        {
            euler.x = std::asin(sinPitch);
            euler.y = std::atan2(2.0f * (qn.w * qn.y + qn.x * qn.z), 1.0f - 2.0f * (qn.x * qn.x + qn.y * qn.y));
            euler.z = std::atan2(2.0f * (qn.w * qn.z + qn.x * qn.y), 1.0f - 2.0f * (qn.x * qn.x + qn.z * qn.z));
        }

        return euler;
    }

}
